# Generated by Django 4.2.13 on 2024-06-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltestfile',
            name='idat',
        ),
        migrations.RemoveField(
            model_name='testfile',
            name='idat',
        ),
        migrations.AddField(
            model_name='order',
            name='external_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
