# Generated by Django 4.2.13 on 2024-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_historicaltestfile_idat_remove_testfile_idat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallaminatorboot',
            name='check_crown_treatment',
        ),
        migrations.RemoveField(
            model_name='laminatorboot',
            name='check_crown_treatment',
        ),
        migrations.AddField(
            model_name='historicallaminatorboot',
            name='crown_treatment_pri',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicallaminatorboot',
            name='crown_treatment_sec',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='laminatorboot',
            name='crown_treatment_pri',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='laminatorboot',
            name='crown_treatment_sec',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
