# Generated by Django 4.2.13 on 2024-06-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleorder',
            name='pre_print_ready',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='pre_print_ready',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
