# Generated by Django 4.2.13 on 2024-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='bob_or_ream',
            field=models.CharField(choices=[('Bobina', 'Bobina'), ('Resma', 'Resma')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='bob_or_ream',
            field=models.CharField(choices=[('Bobina', 'Bobina'), ('Resma', 'Resma')], max_length=10, null=True),
        ),
    ]
