# Generated by Django 4.2.13 on 2024-09-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_plan_options_deincorporaterequest'),
        ('sales', '0004_alter_historicalsaleorder_bob_or_ream_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleorder',
            options={'permissions': [('view_sale_order_confidential', 'Puede ver detalles específicos de Pedidos de compra'), ('approve_sale_order', 'Puede firmar una pedido de compra cómo aprobada'), ('review_sale_order', 'Puede firmar una pedido de compra cómo revisado'), ('archive_sale_order', 'Puede archivar una pedido de compra'), ('view_archive_sale_order', 'Puede ver el archivo pedido de compra'), ('view_deleted_sale_order', 'Puede ver la papelera de pedidos de compra')], 'verbose_name': 'Órden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.CreateModel(
            name='SaleOrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_order_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_order_date', models.CharField(blank=True, max_length=100, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('deincorporate_request', models.BooleanField(default=False)),
                ('by', models.CharField(blank=True, max_length=50, null=True)),
                ('observation', models.TextField(blank=True, max_length=500, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('sale_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treview', to='sales.saleorder')),
                ('suggested_replace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.plan')),
            ],
            options={
                'verbose_name': 'Revisión de pedido',
                'verbose_name_plural': 'Revisiones de pedidos',
            },
        ),
    ]
