# Generated by Django 4.2.13 on 2024-09-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_saleorder_options_saleorderreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleorder',
            options={'permissions': [('view_sale_order_confidential', 'Puede ver detalles específicos de Pedidos de compra'), ('approve_sale_order', 'Puede firmar una pedido de compra cómo aprobada'), ('review_sale_order', 'Puede firmar una pedido de compra cómo revisado'), ('archive_sale_order', 'Puede archivar una pedido de compra'), ('view_archive_sale_order', 'Puede ver el archivo pedido de compra'), ('delete_deleted_sale_order', 'Puede ver la papelera de pedidos de compra'), ('restore_deleted_sale_order', 'Puede ver la papelera de pedidos de compra'), ('view_deleted_sale_order', 'Puede ver la papelera de pedidos de compra')], 'verbose_name': 'Órden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
    ]
