# Generated by Django 4.2.13 on 2024-09-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_saleorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsaleorder',
            name='currency',
            field=models.CharField(choices=[('Bs.', 'Bs.'), ('$', '$')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='currency',
            field=models.CharField(choices=[('Bs.', 'Bs.'), ('$', '$')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsaleorder',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('m', 'm'), ('m²', 'm²'), ('ud', 'ud')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('m', 'm'), ('m²', 'm²'), ('ud', 'ud')], max_length=3, null=True),
        ),
    ]
