# Generated by Django 4.2.13 on 2025-03-14 13:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '__first__'),
        ('home', '0010_deincorporaterequest_rejected'),
        ('sales', '0007_historicalsaleorder_currency_saleorder_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('company', models.CharField(blank=True, choices=[('mcl', 'Morrocel'), ('crx', 'Curex')], max_length=3, null=True)),
                ('product', models.CharField(max_length=100, null=True)),
                ('printed_sample', models.BooleanField(blank=True, default=False, null=True)),
                ('mechanical_plan', models.BooleanField(blank=True, default=False, null=True)),
                ('technichal_specs', models.BooleanField(blank=True, default=False, null=True)),
                ('arts', models.BooleanField(blank=True, default=False, null=True)),
                ('design', models.CharField(blank=True, choices=[('yim', 'Impreso'), ('nim', 'Sin Impresión')], max_length=3, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('rev', 'Impreso Reverso'), ('sfc', 'Impreso Superficie'), ('lam', 'Laminado'), ('mon', 'Monocapa')], max_length=3, null=True)),
                ('observation', django_quill.fields.QuillField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.client')),
                ('documents', models.ManyToManyField(blank=True, to='documents.document')),
            ],
            options={
                'verbose_name': 'Solicitudes de Pruebas',
                'verbose_name_plural': 'Solicitudes de Pruebas',
            },
        ),
        migrations.CreateModel(
            name='SalesStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999.0)])),
                ('thickness', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999.0)])),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.materialtype')),
                ('s_test_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.salestestrequest')),
            ],
            options={
                'verbose_name': 'Estrucura',
                'verbose_name_plural': 'Estructura',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSalesTestRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('company', models.CharField(blank=True, choices=[('mcl', 'Morrocel'), ('crx', 'Curex')], max_length=3, null=True)),
                ('product', models.CharField(max_length=100, null=True)),
                ('printed_sample', models.BooleanField(blank=True, default=False, null=True)),
                ('mechanical_plan', models.BooleanField(blank=True, default=False, null=True)),
                ('technichal_specs', models.BooleanField(blank=True, default=False, null=True)),
                ('arts', models.BooleanField(blank=True, default=False, null=True)),
                ('design', models.CharField(blank=True, choices=[('yim', 'Impreso'), ('nim', 'Sin Impresión')], max_length=3, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('rev', 'Impreso Reverso'), ('sfc', 'Impreso Superficie'), ('lam', 'Laminado'), ('mon', 'Monocapa')], max_length=3, null=True)),
                ('observation', django_quill.fields.QuillField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.client')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Solicitudes de Pruebas',
                'verbose_name_plural': 'historical Solicitudes de Pruebas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
