from setuptools import setup, find_packages

setup(
    name='SUMI',
    version='0.1.0',
    author='Your Name',
    author_email='your.email@example.com',
    description='A short description of your project.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/your_username/your_project_name',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Django==4.2.13',
        'gunicorn',
        'whitenoise',
        'python-dotenv',
        'django-filter',
        'django-quill-editor',
        'django-simple-history',
        'mssql-django',
        'pillow',
        'Brotli',
        'waitress',
        'django-cleanup'
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
    ],
    python_requires='>=3.6',
)
