# Generated by Django 4.2.13 on 2024-08-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preprint',
            options={'permissions': [('pp_pdf_check', 'Puede enviar PDF para aprobar'), ('pp_pdf_approval', 'Puede aprobar o rechazar PDF'), ('pp_pc_check', 'Puede enviar PC para aprobar'), ('pp_pc_approval', 'Puede aprobar o rechazar PC'), ('pp_plate', 'Puede verificar Planchas')], 'verbose_name': 'Estado de Pre Prensa', 'verbose_name_plural': 'Estados de Pre Prensa'},
        ),
        
    ]
