# Generated by Django 4.2.13 on 2024-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'permissions': [('sign_plan', 'Puede firmar un plan cómo revisado'), ('disincorporate_plan', 'Puede eliminar un plan de calidad archivado'), ('view_archive_plan', 'Puede ver el archivo de planes de calidad'), ('archive_plan', 'Puede archivar un plan de calidad'), ('delete_archive_plan', 'Puede eliminar un plan de calidad permanentemente')], 'verbose_name': 'Plan de Calidad', 'verbose_name_plural': 'Planes de Calidad'},
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='disicomop_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='disicomop_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='disicomop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='disincorporated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='disicomop_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='disicomop_reason',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='disicomop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='disincorporated',
            field=models.BooleanField(default=False),
        ),
    ]
