# Generated by Django 4.2.13 on 2024-07-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_plan_options_historicalplan_disicomop_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstructure',
            name='t_counts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalstructure',
            name='w_counts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='t_counts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='w_counts',
            field=models.BooleanField(default=True),
        ),
    ]
