# Generated by Django 4.2.13 on 2024-08-27 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_historicalstructure_t_counts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rif_num',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{7}+-[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='rif_type',
            field=models.CharField(choices=[('MC', 'MC'), ('J', 'J'), ('V', 'V'), ('P', 'P'), ('E', 'E'), ('G', 'G'), ('C', 'C')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='rif_num',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{7}+-[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='rif_type',
            field=models.CharField(choices=[('MC', 'MC'), ('J', 'J'), ('V', 'V'), ('P', 'P'), ('E', 'E'), ('G', 'G'), ('C', 'C')], max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('rif_type', 'rif_num')},
        ),
    ]
