# Generated by Django 4.2.13 on 2024-08-27 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_client_rif_num_alter_client_rif_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalclient',
            name='rif_num',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{8}+-[0-9]+$')]),
        ),
    ]
