# Generated by Django 4.2.13 on 2024-09-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_client_rif_num_alter_historicalclient_rif_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'permissions': [('sign_plan', 'Puede firmar un plan cómo revisado'), ('view_disincorporate_plan', 'Puede ver planes de calidad desincorporados'), ('disincorporate_plan', 'Puede desincorporar un plan de calidad'), ('view_archive_plan', 'Puede ver el archivo de planes de calidad'), ('archive_plan', 'Puede archivar un plan de calidad'), ('delete_archive_plan', 'Puede eliminar un plan de calidad permanentemente')], 'verbose_name': 'Plan de Calidad', 'verbose_name_plural': 'Planes de Calidad'},
        ),
        migrations.CreateModel(
            name='DeincorporateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deincorporate_request', to='home.plan')),
            ],
            options={
                'verbose_name': 'Solicitud de Desincorporación de Plan de Calidad',
                'verbose_name_plural': 'Solicitudes de Desincorpor ación de Planes de Calidad',
            },
        ),
    ]
