# Generated by Django 4.2.13 on 2024-09-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_saleorder_options_saleorderreview'),
        ('home', '0008_alter_plan_options_deincorporaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deincorporaterequest',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.saleorderreview'),
        ),
    ]
