# Generated by Django 4.2.13 on 2024-09-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_deincorporaterequest_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='deincorporaterequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
