# Generated by Django 4.2.13 on 2024-06-13 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0002_historicalsaleorder_pre_print_ready_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrePrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.BooleanField(default=False, null=True)),
                ('pdf_date', models.DateTimeField(blank=True, null=True)),
                ('pdf_approval', models.BooleanField(default=False, null=True)),
                ('pdf_approval_date', models.DateTimeField(blank=True, null=True)),
                ('pc', models.BooleanField(default=False, null=True)),
                ('pc_date', models.DateTimeField(blank=True, null=True)),
                ('pc_approval', models.BooleanField(default=False, null=True)),
                ('pc_approval_date', models.DateTimeField(blank=True, null=True)),
                ('plates', models.BooleanField(default=False, null=True)),
                ('plates_date', models.DateTimeField(blank=True, null=True)),
                ('sale_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_print', to='sales.saleorder')),
            ],
            options={
                'verbose_name': 'Estado de Pre Prensa',
                'verbose_name_plural': 'Estados de Pre Prensa',
                'permissions': [('pp_pdf_check', 'Puede enviar PDF para aprobar'), ('pp_pdf_approval', 'Puede aprobar PDF'), ('pp_pc_check', 'Puede enviar PC para aprobar'), ('pp_pc_approval', 'Puede aprobar PC'), ('pp_plate', 'Puede verificar Planchas')],
            },
        ),
    ]
