# Generated by Django 4.2.13 on 2025-03-14 13:34

from django.db import migrations, models
import documents.utils
import documents.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to=documents.utils.custom_upload_to, validators=[documents.validators.validate_file_type, documents.validators.validate_file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
