# Generated by Django 4.2.13 on 2024-06-11 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestrequest',
            name='tolerance',
            field=models.IntegerField(default=10, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='tolerance',
            field=models.IntegerField(default=10, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
