# Generated by Django 4.2.13 on 2024-06-21 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_alter_historicaltestrequest_tolerance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryelement',
            old_name='code_page_encodebarcode',
            new_name='barcode',
        ),
        migrations.RenameField(
            model_name='entryelement',
            old_name='other',
            new_name='cpe',
        ),
        migrations.RenameField(
            model_name='entryelement',
            old_name='other_description',
            new_name='ee_other_description',
        ),
        migrations.RemoveField(
            model_name='historicaltestrequest',
            name='reverse_over',
        ),
        migrations.RemoveField(
            model_name='historicaltestrequest',
            name='surface_over',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='reverse_over',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='surface_over',
        ),
        migrations.AddField(
            model_name='entryelement',
            name='ee_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='involved_processes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='lr_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='lr_other_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='sc_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='sc_other_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicaltestrequest',
            name='entry_element',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='essays.entryelement'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='entry_element',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_element', to='essays.entryelement'),
        ),
        migrations.AlterField(
            model_name='historicallaminatorboot',
            name='check_crown_treatment',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='historicaltestrequest',
            name='lenght_photo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='historicaltestrequest',
            name='width_photo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='laminatorboot',
            name='check_crown_treatment',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='lenght_photo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='width_photo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)]),
        ),
    ]
