# Generated by Django 4.2.13 on 2024-06-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0004_rename_code_page_encodebarcode_entryelement_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallaminatorboot',
            name='check_crown_treatment',
        ),
        migrations.RemoveField(
            model_name='laminatorboot',
            name='check_crown_treatment',
        ),
        migrations.AddField(
            model_name='historicallaminatorboot',
            name='crown_treatment_pri',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicallaminatorboot',
            name='crown_treatment_sec',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='laminatorboot',
            name='crown_treatment_pri',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='laminatorboot',
            name='crown_treatment_sec',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='entry_element',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_element', to='essays.entryelement'),
        ),
    ]
