# Generated by Django 4.2.13 on 2024-08-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0006_historicalteststructure_t_counts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryelement',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaltestrequest',
            name='origin',
            field=models.CharField(choices=[('new', 'Nueva Estructura'), ('upd', 'Cambio de Estructura'), ('int', 'Prueba Interna'), ('mat', 'Evaluación de Materia Prima / Proveedor')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='origin',
            field=models.CharField(choices=[('new', 'Nueva Estructura'), ('upd', 'Cambio de Estructura'), ('int', 'Prueba Interna'), ('mat', 'Evaluación de Materia Prima / Proveedor')], max_length=3, null=True),
        ),
    ]
