# Generated by Django 4.2.13 on 2024-08-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0007_alter_entryelement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryelement',
            name='involved_processes',
        ),
        migrations.AddField(
            model_name='entryelement',
            name='bagging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='covering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='cutting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='gazette',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='iso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='lamination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='mounting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='norms_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='printing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryelement',
            name='reaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltestrequest',
            name='photocell_side',
            field=models.CharField(blank=True, choices=[('l', 'Fotocelda lado izquierdo'), ('r', 'Fotocelda lado derecho')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='photocell_side',
            field=models.CharField(blank=True, choices=[('l', 'Fotocelda lado izquierdo'), ('r', 'Fotocelda lado derecho')], max_length=1, null=True),
        ),
    ]
