# Generated by Django 4.2.13 on 2024-08-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0008_remove_entryelement_involved_processes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrequest',
            options={'permissions': [('sign_testrequest', 'Puede firmar una solicitud de prueba cómo revisada'), ('view_archived_testrequest', 'Puede ver el archivo de solicitudes de prueba'), ('archive_testrequest', 'Puede archivar una solicitud de prueba'), ('unarchive_testrequest', 'Puede desarchivar una solicitud de prueba'), ('view_deleted_testrequest', 'Puede ver la papelera de solicitudes de prueba'), ('delete_true_testrequest', 'Puede eliminar permanentemenete una solicitud de prueba'), ('restore_testrequest', 'Puede restaurar una solicitud de prueba de la papelera'), ('close_testrequest', 'Puede Cerrar Un expediente de Pruebas y enviar a IDAT'), ('open_testrequest', 'Puede Abrir Un expediente de Pruebas y enviar a IDAT')], 'verbose_name': 'Solicitud de Prueba', 'verbose_name_plural': 'Solicitudes de Prueba'},
        ),
        migrations.AddField(
            model_name='historicaltestrequest',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltestrequest',
            name='archived_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltestrequest',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltestrequest',
            name='closed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='archived_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='closed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryelement',
            name='elaborator',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
