# Generated by Django 4.2.13 on 2024-09-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0010_historicalprinterboot_photocell_side_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrequest',
            options={'permissions': [('view_working_testrequest', 'Puede firmar una solicitud de prueba cómo revisada'), ('sign_testrequest', 'Puede firmar una solicitud de prueba cómo revisada'), ('view_archived_testrequest', 'Puede ver el archivo de solicitudes de prueba'), ('archive_testrequest', 'Puede archivar una solicitud de prueba'), ('unarchive_testrequest', 'Puede desarchivar una solicitud de prueba'), ('view_deleted_testrequest', 'Puede ver la papelera de solicitudes de prueba'), ('delete_true_testrequest', 'Puede eliminar permanentemenete una solicitud de prueba'), ('restore_testrequest', 'Puede restaurar una solicitud de prueba de la papelera'), ('close_testrequest', 'Puede Cerrar Un expediente de Pruebas y enviar a IDAT'), ('open_testrequest', 'Puede Abrir Un expediente de Pruebas y enviar a IDAT')], 'verbose_name': 'Solicitud de Prueba', 'verbose_name_plural': 'Solicitudes de Prueba'},
        ),
    ]
