# Generated by Django 4.2.13 on 2025-03-14 13:34

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '__first__'),
        ('essays', '0012_alter_testrequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensions', models.BooleanField(default=False)),
                ('technical_specs', models.BooleanField(default=False)),
                ('delivery_time', models.BooleanField(default=False)),
                ('ae_other', models.BooleanField(default=False)),
                ('ae_other_description', models.CharField(blank=True, max_length=200, null=True)),
                ('functionallity_and_performance', models.TextField(blank=True, default='', null=True)),
                ('replicavility', models.BooleanField(default=False)),
                ('replicavility_description', models.CharField(blank=True, max_length=200, null=True)),
                ('lab_analysis', models.CharField(choices=[('apr', 'Aprobado'), ('reg', 'Regular'), ('def', 'Deficiente'), ('noc', 'No cumple'), ('noa', 'No aplica')], max_length=3, null=True)),
                ('machinability', models.CharField(choices=[('apr', 'Aprobado'), ('reg', 'Regular'), ('def', 'Deficiente'), ('noc', 'No cumple'), ('noa', 'No aplica')], max_length=3, null=True)),
                ('handling', models.CharField(choices=[('apr', 'Aprobado'), ('reg', 'Regular'), ('def', 'Deficiente'), ('noc', 'No cumple'), ('noa', 'No aplica')], max_length=3, null=True)),
                ('shelf_life', models.CharField(choices=[('apr', 'Aprobado'), ('reg', 'Regular'), ('def', 'Deficiente'), ('noc', 'No cumple'), ('noa', 'No aplica'), ('eva', 'En evaluacion')], max_length=3, null=True)),
                ('shelf_life_date', models.DateField(blank=True, null=True)),
                ('delivery', models.CharField(choices=[('apr', 'Aprobado'), ('reg', 'Regular'), ('def', 'Deficiente'), ('noc', 'No cumple'), ('noa', 'No aplica')], max_length=3, null=True)),
                ('storage', models.CharField(choices=[('apr', 'Aprobado'), ('reg', 'Regular'), ('def', 'Deficiente'), ('noc', 'No cumple'), ('noa', 'No aplica')], max_length=3, null=True)),
                ('technical_assistance', models.CharField(choices=[('apr', 'Aprobado'), ('reg', 'Regular'), ('def', 'Deficiente'), ('noc', 'No cumple'), ('noa', 'No aplica')], max_length=3, null=True)),
                ('after_sales_service', models.CharField(choices=[('apr', 'Aprobado'), ('reg', 'Regular'), ('def', 'Deficiente'), ('noc', 'No cumple'), ('noa', 'No aplica')], max_length=3, null=True)),
                ('failure', models.BooleanField(default=False)),
                ('failure_description', models.CharField(blank=True, max_length=200, null=True)),
                ('failure_consequence', models.CharField(blank=True, max_length=200, null=True)),
                ('guarantee', models.BooleanField(default=False)),
                ('guarantee_description', models.CharField(blank=True, max_length=200, null=True)),
                ('elaborator', models.CharField(max_length=100, null=True)),
                ('reviewer', models.CharField(blank=True, max_length=100, null=True)),
                ('observation', django_quill.fields.QuillField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Elementos de salida del diseño y desarrollo',
                'verbose_name_plural': 'Elementos de salida del diseño y desarrollo',
            },
        ),
        migrations.AlterModelOptions(
            name='testrequest',
            options={'permissions': [('view_working_testrequest', 'Puede firmar una solicitud de prueba cómo revisada'), ('sign_testrequest', 'Puede firmar una solicitud de prueba cómo revisada'), ('view_archived_testrequest', 'Puede ver el archivo de solicitudes de prueba'), ('archive_testrequest', 'Puede archivar una solicitud de prueba'), ('unarchive_testrequest', 'Puede desarchivar una solicitud de prueba'), ('view_deleted_testrequest', 'Puede ver la papelera de solicitudes de prueba'), ('delete_true_testrequest', 'Puede eliminar permanentemenete una solicitud de prueba'), ('restore_testrequest', 'Puede restaurar una solicitud de prueba de la papelera'), ('close_testrequest', 'Puede Cerrar Un expediente de Pruebas y enviar a IDAT'), ('open_testrequest', 'Puede Abrir Un expediente de Pruebas y enviar a IDAT')], 'verbose_name': 'Solicitud de Prueba', 'verbose_name_plural': 'Solicitudes de Prueba'},
        ),
        migrations.AddField(
            model_name='entryelement',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.document'),
        ),
    ]
