# Generated by Django 4.2.13 on 2025-03-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salestestrequest_salesstructure_and_more'),
        ('documents', '__first__'),
        ('essays', '0013_exitelement_alter_testrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryelement',
            name='sales_test_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salestestrequest'),
        ),
        migrations.AlterField(
            model_name='historicaltestrequest',
            name='photocell_side',
            field=models.CharField(blank=True, choices=[('l', 'Fotocelda lado izquierdo'), ('r', 'Fotocelda lado derecho'), ('b', 'Fotocelda ambos lados')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='entry_element',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_element', to='essays.entryelement'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='photocell_side',
            field=models.CharField(blank=True, choices=[('l', 'Fotocelda lado izquierdo'), ('r', 'Fotocelda lado derecho'), ('b', 'Fotocelda ambos lados')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='exitelement',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.document'),
        ),
        migrations.AddField(
            model_name='exitelement',
            name='test_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='exit_element', to='essays.testrequest', verbose_name='Solicitud de prueba'),
        ),
    ]
