# Generated by Django 4.2.13 on 2025-06-11 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0016_artentryelement_artexitelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artrequest',
            name='entry_element',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_entry_element', to='essays.artentryelement'),
        ),
        migrations.AlterField(
            model_name='historicalartrequest',
            name='entry_element',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='essays.artentryelement'),
        ),
    ]
