# Generated by Django 5.2.1 on 2025-06-12 16:24

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0017_alter_artrequest_entry_element_and_more'),
        ('home', '0010_deincorporaterequest_rejected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=11, null=True)),
                ('weight', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999.0)])),
                ('w_counts', models.BooleanField(default=True)),
                ('thickness', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999.0)])),
                ('t_counts', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('from_production', models.CharField(blank=True, max_length=100, null=True)),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.materialtype')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.provider')),
                ('test_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='essays.artrequest')),
            ],
            options={
                'verbose_name': 'Estructura',
                'verbose_name_plural': 'Estructuras',
            },
        ),
        migrations.CreateModel(
            name='HistoricalArtStructure',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=11, null=True)),
                ('weight', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999.0)])),
                ('w_counts', models.BooleanField(default=True)),
                ('thickness', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999.0)])),
                ('t_counts', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('from_production', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.materialtype')),
                ('provider', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='home.provider')),
                ('test_request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='essays.artrequest')),
            ],
            options={
                'verbose_name': 'historical Estructura',
                'verbose_name_plural': 'historical Estructuras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
