# Generated by Django 5.2.1 on 2025-06-16 19:17

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0018_artstructure_historicalartstructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtTechnicalSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('observation', django_quill.fields.QuillField(blank=True, null=True)),
                ('boss', models.CharField(blank=True, max_length=30, null=True)),
                ('art_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essays.artrequest')),
                ('quality_analist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='essays.qualityanalyst')),
            ],
        ),
    ]
