# Generated by Django 4.2.13 on 2025-07-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0019_arttechnicalspecs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutterboot',
            name='art_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essays.artrequest'),
        ),
        migrations.AddField(
            model_name='historicalcutterboot',
            name='art_request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='essays.artrequest'),
        ),
        migrations.AddField(
            model_name='historicallaminatorboot',
            name='art_request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='essays.artrequest'),
        ),
        migrations.AddField(
            model_name='historicalprinterboot',
            name='art_request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='essays.artrequest'),
        ),
        migrations.AddField(
            model_name='laminatorboot',
            name='art_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essays.artrequest'),
        ),
        migrations.AddField(
            model_name='printerboot',
            name='art_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essays.artrequest'),
        ),
    ]
