# Generated by Django 4.2.13 on 2025-07-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0020_cutterboot_art_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artstructure',
            old_name='test_request',
            new_name='art_request',
        ),
        migrations.RenameField(
            model_name='historicalartstructure',
            old_name='test_request',
            new_name='art_request',
        ),
    ]
