# Generated by Django 4.2.13 on 2025-07-04 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0021_rename_test_request_artstructure_art_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annex',
            name='art_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essays.artrequest'),
        ),
        migrations.AddField(
            model_name='historicaltestfile',
            name='boot_c',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='essays.cutterboot'),
        ),
        migrations.AddField(
            model_name='testfile',
            name='boot_c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essays.cutterboot'),
        ),
    ]
