# Generated by Django 4.2.13 on 2025-07-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_deincorporaterequest_rejected'),
        ('essays', '0022_annex_art_request_historicaltestfile_boot_c_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=20, null=True)),
                ('requesting_company', models.CharField(default='Morocel', max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('net_content', models.CharField(blank=True, max_length=100, null=True)),
                ('requester', models.CharField(blank=True, max_length=100, null=True)),
                ('supplied_material', models.CharField(blank=True, choices=[('muestra Impresa', 'Muestra Impresa'), ('plano Mecánico', 'Plano Mecánico'), ('otro', 'Otro')], max_length=20, null=True)),
                ('supplied_material_other', models.CharField(blank=True, max_length=100, null=True)),
                ('printer', models.CharField(blank=True, choices=[('novoflex', 'Novoflex'), ('olympia', 'Olympia'), ('alina', 'Alina')], max_length=20, null=True)),
                ('substrate_to_print', models.CharField(default='Aluminum', max_length=100)),
                ('print_type', models.CharField(blank=True, choices=[('reverso', 'Reverso'), ('superficie', 'Superficie')], max_length=20, null=True)),
                ('product_structure', models.CharField(default='INK, ALUMINUM, RESIN', max_length=100)),
                ('printed_development_mm', models.FloatField(blank=True, null=True)),
                ('package_unit_length_mm', models.FloatField(blank=True, null=True)),
                ('k', models.FloatField(blank=True, null=True)),
                ('distortion_percent', models.FloatField(blank=True, null=True)),
                ('distorted_development_mm', models.FloatField(blank=True, null=True)),
                ('adjusted_printed_unit_length_mm', models.FloatField(blank=True, null=True)),
                ('repeats_per_development', models.IntegerField(blank=True, null=True)),
                ('client_bobbin_width_mm', models.FloatField(blank=True, null=True)),
                ('plant_bobbin_width_mm', models.FloatField(blank=True, null=True)),
                ('repeats_per_printed_width', models.IntegerField(blank=True, null=True)),
                ('printed_width_mm', models.FloatField(blank=True, null=True)),
                ('distance_between_repeats_width_mm', models.FloatField(blank=True, null=True)),
                ('package_unit_width_mm', models.FloatField(blank=True, null=True)),
                ('plate_type', models.CharField(blank=True, max_length=100, null=True)),
                ('thickness', models.CharField(blank=True, max_length=50, null=True)),
                ('photocell', models.CharField(blank=True, choices=[('no', 'No'), ('si', 'Sí')], max_length=3, null=True)),
                ('photocell_width_mm', models.FloatField(blank=True, null=True)),
                ('photocell_length_mm', models.FloatField(blank=True, null=True)),
                ('distance_between_photocells_mm', models.FloatField(blank=True, null=True)),
                ('tolerance_mm', models.FloatField(blank=True, null=True)),
                ('photocell_colors', models.CharField(blank=True, max_length=100, null=True)),
                ('total_colors', models.IntegerField(blank=True, null=True)),
                ('cut_bar_colors', models.CharField(blank=True, max_length=100, null=True)),
                ('displacement', models.CharField(blank=True, choices=[('no', 'No'), ('si', 'Sí'), ('zigzag', 'Zig-Zag'), ('escalonado', 'Escalonado')], max_length=12, null=True)),
                ('roll_down_suggestions', models.TextField(blank=True, null=True)),
                ('art_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='essays.artrequest')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.client')),
            ],
            options={
                'verbose_name': 'Analisis de arte',
                'verbose_name_plural': 'Analisis de artes',
            },
        ),
    ]
