# Generated by Django 4.2.13 on 2025-07-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0023_artanalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artanalysis',
            name='net_content',
        ),
        migrations.RemoveField(
            model_name='artanalysis',
            name='requester',
        ),
    ]
