# Generated by Django 4.2.13 on 2025-07-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0024_remove_artanalysis_net_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artanalysis',
            name='anilox_angle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artanalysis',
            name='anilox_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artanalysis',
            name='anilox_l_cm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artanalysis',
            name='double_sided_thickness',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artanalysis',
            name='double_sided_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artanalysis',
            name='image_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artanalysis',
            name='min_point_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artanalysis',
            name='printing_unit_colors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artanalysis',
            name='screen_lpi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
