# Generated by Django 4.2.13 on 2025-07-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0026_alter_artrequest_options_remove_artrequest_art_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artrequest',
            name='number',
            field=models.CharField(blank=True, help_text="Número único que identifica la solicitud. Ej: 'REQ-2025-001'", max_length=20, null=True, verbose_name='Número de Solicitud'),
        ),
        migrations.AddField(
            model_name='historicalartrequest',
            name='number',
            field=models.CharField(blank=True, help_text="Número único que identifica la solicitud. Ej: 'REQ-2025-001'", max_length=20, null=True, verbose_name='Número de Solicitud'),
        ),
    ]
