# Generated by Django 4.2.13 on 2025-07-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0027_artrequest_number_historicalartrequest_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artrequest',
            old_name='requesting_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='historicalartrequest',
            old_name='requesting_company',
            new_name='company',
        ),
    ]
