# Generated by Django 4.2.13 on 2025-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0028_rename_requesting_company_artrequest_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artrequest',
            name='company',
            field=models.CharField(blank=True, choices=[('mcl', 'Morrocel'), ('crx', 'Curex')], help_text='Compañía que solicita el trabajo. Ej: "Morocel"', max_length=255, null=True, verbose_name='Empresa solicitante'),
        ),
        migrations.AlterField(
            model_name='historicalartrequest',
            name='company',
            field=models.CharField(blank=True, choices=[('mcl', 'Morrocel'), ('crx', 'Curex')], help_text='Compañía que solicita el trabajo. Ej: "Morocel"', max_length=255, null=True, verbose_name='Empresa solicitante'),
        ),
    ]
